//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.6.3
//     from Assets/ControlMapping.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ControlMapping: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ControlMapping()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ControlMapping"",
    ""maps"": [
        {
            ""name"": ""Mapping"",
            ""id"": ""850f18d4-9c8c-43e4-9413-8de09d4a3304"",
            ""actions"": [
                {
                    ""name"": ""GraceWhite"",
                    ""type"": ""Value"",
                    ""id"": ""587ec02d-c1ff-44da-bd2b-7f77e94d8130"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""GraceLila"",
                    ""type"": ""Value"",
                    ""id"": ""6af38fa6-58a9-4925-8ab7-ebeaac19047e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""BabyBalenciaga"",
                    ""type"": ""Value"",
                    ""id"": ""93f12456-44b7-4f51-b035-f9720a3e157a"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""MuscleMan"",
                    ""type"": ""Button"",
                    ""id"": ""faa11afc-56eb-4323-a9b9-463d3158e5f3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Tera"",
                    ""type"": ""Value"",
                    ""id"": ""f61850d7-515b-401e-8309-2b19fdbf013e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""BabyBalensiagaFlying"",
                    ""type"": ""Value"",
                    ""id"": ""c6da6fb0-f944-4620-8112-884cc017b308"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""FireMan"",
                    ""type"": ""Value"",
                    ""id"": ""9c3c0f7b-cda9-4cab-9b4e-b5f393f16760"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CameraMoveAround"",
                    ""type"": ""Value"",
                    ""id"": ""61c323d3-5833-442f-a051-a8f445507993"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""CameraOutIn"",
                    ""type"": ""Value"",
                    ""id"": ""62c478e5-ec12-4e55-977d-d2f4fecdfbf6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ResetPos"",
                    ""type"": ""Value"",
                    ""id"": ""cdc21792-8028-451a-939f-c3d68263c1d8"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""ResetRot"",
                    ""type"": ""Value"",
                    ""id"": ""2e6898c5-5de2-4e20-a371-71c6e4cf3375"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""1adffb89-51c8-423c-8c0d-50fd3a26bb10"",
                    ""path"": ""<XInputController>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MappingScheme"",
                    ""action"": ""GraceLila"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""28a40e71-7c95-45bd-945f-b9ded2d24f1e"",
                    ""path"": ""<XInputController>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MappingScheme"",
                    ""action"": ""BabyBalenciaga"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""62628364-6ff4-4c05-83a4-182586a37f38"",
                    ""path"": ""<XInputController>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MappingScheme"",
                    ""action"": ""GraceWhite"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""42726c79-45f1-4e41-b9dd-8af822d1a77f"",
                    ""path"": ""<XInputController>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MappingScheme"",
                    ""action"": ""Tera"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""987b3fb1-98f4-42ae-b5b9-16e56ac40d33"",
                    ""path"": ""<XInputController>/dpad/down"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""MuscleMan"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""af2b890d-6d15-4ec3-8e70-e086e6067148"",
                    ""path"": ""<XInputController>/rightStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MappingScheme"",
                    ""action"": ""CameraMoveAround"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""10f75561-106d-4016-a93a-505111751544"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MappingScheme"",
                    ""action"": ""CameraOutIn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""caf3359d-9ae0-4223-9e12-05d05eecb110"",
                    ""path"": ""<XInputController>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ResetPos"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""af699595-381f-4e48-ba58-ba5c0b24c4af"",
                    ""path"": ""<XInputController>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""ResetRot"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""07336e8a-6088-4435-9708-8147e358d9fb"",
                    ""path"": ""<XInputController>/dpad/up"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MappingScheme"",
                    ""action"": ""BabyBalensiagaFlying"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""6d35322c-b976-480c-8b18-a83f7a1f9ab0"",
                    ""path"": ""<XInputController>/dpad/right"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": ""MappingScheme"",
                    ""action"": ""FireMan"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": [
        {
            ""name"": ""MappingScheme"",
            ""bindingGroup"": ""MappingScheme"",
            ""devices"": [
                {
                    ""devicePath"": ""<XInputController>"",
                    ""isOptional"": false,
                    ""isOR"": false
                }
            ]
        }
    ]
}");
        // Mapping
        m_Mapping = asset.FindActionMap("Mapping", throwIfNotFound: true);
        m_Mapping_GraceWhite = m_Mapping.FindAction("GraceWhite", throwIfNotFound: true);
        m_Mapping_GraceLila = m_Mapping.FindAction("GraceLila", throwIfNotFound: true);
        m_Mapping_BabyBalenciaga = m_Mapping.FindAction("BabyBalenciaga", throwIfNotFound: true);
        m_Mapping_MuscleMan = m_Mapping.FindAction("MuscleMan", throwIfNotFound: true);
        m_Mapping_Tera = m_Mapping.FindAction("Tera", throwIfNotFound: true);
        m_Mapping_BabyBalensiagaFlying = m_Mapping.FindAction("BabyBalensiagaFlying", throwIfNotFound: true);
        m_Mapping_FireMan = m_Mapping.FindAction("FireMan", throwIfNotFound: true);
        m_Mapping_CameraMoveAround = m_Mapping.FindAction("CameraMoveAround", throwIfNotFound: true);
        m_Mapping_CameraOutIn = m_Mapping.FindAction("CameraOutIn", throwIfNotFound: true);
        m_Mapping_ResetPos = m_Mapping.FindAction("ResetPos", throwIfNotFound: true);
        m_Mapping_ResetRot = m_Mapping.FindAction("ResetRot", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Mapping
    private readonly InputActionMap m_Mapping;
    private List<IMappingActions> m_MappingActionsCallbackInterfaces = new List<IMappingActions>();
    private readonly InputAction m_Mapping_GraceWhite;
    private readonly InputAction m_Mapping_GraceLila;
    private readonly InputAction m_Mapping_BabyBalenciaga;
    private readonly InputAction m_Mapping_MuscleMan;
    private readonly InputAction m_Mapping_Tera;
    private readonly InputAction m_Mapping_BabyBalensiagaFlying;
    private readonly InputAction m_Mapping_FireMan;
    private readonly InputAction m_Mapping_CameraMoveAround;
    private readonly InputAction m_Mapping_CameraOutIn;
    private readonly InputAction m_Mapping_ResetPos;
    private readonly InputAction m_Mapping_ResetRot;
    public struct MappingActions
    {
        private @ControlMapping m_Wrapper;
        public MappingActions(@ControlMapping wrapper) { m_Wrapper = wrapper; }
        public InputAction @GraceWhite => m_Wrapper.m_Mapping_GraceWhite;
        public InputAction @GraceLila => m_Wrapper.m_Mapping_GraceLila;
        public InputAction @BabyBalenciaga => m_Wrapper.m_Mapping_BabyBalenciaga;
        public InputAction @MuscleMan => m_Wrapper.m_Mapping_MuscleMan;
        public InputAction @Tera => m_Wrapper.m_Mapping_Tera;
        public InputAction @BabyBalensiagaFlying => m_Wrapper.m_Mapping_BabyBalensiagaFlying;
        public InputAction @FireMan => m_Wrapper.m_Mapping_FireMan;
        public InputAction @CameraMoveAround => m_Wrapper.m_Mapping_CameraMoveAround;
        public InputAction @CameraOutIn => m_Wrapper.m_Mapping_CameraOutIn;
        public InputAction @ResetPos => m_Wrapper.m_Mapping_ResetPos;
        public InputAction @ResetRot => m_Wrapper.m_Mapping_ResetRot;
        public InputActionMap Get() { return m_Wrapper.m_Mapping; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MappingActions set) { return set.Get(); }
        public void AddCallbacks(IMappingActions instance)
        {
            if (instance == null || m_Wrapper.m_MappingActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MappingActionsCallbackInterfaces.Add(instance);
            @GraceWhite.started += instance.OnGraceWhite;
            @GraceWhite.performed += instance.OnGraceWhite;
            @GraceWhite.canceled += instance.OnGraceWhite;
            @GraceLila.started += instance.OnGraceLila;
            @GraceLila.performed += instance.OnGraceLila;
            @GraceLila.canceled += instance.OnGraceLila;
            @BabyBalenciaga.started += instance.OnBabyBalenciaga;
            @BabyBalenciaga.performed += instance.OnBabyBalenciaga;
            @BabyBalenciaga.canceled += instance.OnBabyBalenciaga;
            @MuscleMan.started += instance.OnMuscleMan;
            @MuscleMan.performed += instance.OnMuscleMan;
            @MuscleMan.canceled += instance.OnMuscleMan;
            @Tera.started += instance.OnTera;
            @Tera.performed += instance.OnTera;
            @Tera.canceled += instance.OnTera;
            @BabyBalensiagaFlying.started += instance.OnBabyBalensiagaFlying;
            @BabyBalensiagaFlying.performed += instance.OnBabyBalensiagaFlying;
            @BabyBalensiagaFlying.canceled += instance.OnBabyBalensiagaFlying;
            @FireMan.started += instance.OnFireMan;
            @FireMan.performed += instance.OnFireMan;
            @FireMan.canceled += instance.OnFireMan;
            @CameraMoveAround.started += instance.OnCameraMoveAround;
            @CameraMoveAround.performed += instance.OnCameraMoveAround;
            @CameraMoveAround.canceled += instance.OnCameraMoveAround;
            @CameraOutIn.started += instance.OnCameraOutIn;
            @CameraOutIn.performed += instance.OnCameraOutIn;
            @CameraOutIn.canceled += instance.OnCameraOutIn;
            @ResetPos.started += instance.OnResetPos;
            @ResetPos.performed += instance.OnResetPos;
            @ResetPos.canceled += instance.OnResetPos;
            @ResetRot.started += instance.OnResetRot;
            @ResetRot.performed += instance.OnResetRot;
            @ResetRot.canceled += instance.OnResetRot;
        }

        private void UnregisterCallbacks(IMappingActions instance)
        {
            @GraceWhite.started -= instance.OnGraceWhite;
            @GraceWhite.performed -= instance.OnGraceWhite;
            @GraceWhite.canceled -= instance.OnGraceWhite;
            @GraceLila.started -= instance.OnGraceLila;
            @GraceLila.performed -= instance.OnGraceLila;
            @GraceLila.canceled -= instance.OnGraceLila;
            @BabyBalenciaga.started -= instance.OnBabyBalenciaga;
            @BabyBalenciaga.performed -= instance.OnBabyBalenciaga;
            @BabyBalenciaga.canceled -= instance.OnBabyBalenciaga;
            @MuscleMan.started -= instance.OnMuscleMan;
            @MuscleMan.performed -= instance.OnMuscleMan;
            @MuscleMan.canceled -= instance.OnMuscleMan;
            @Tera.started -= instance.OnTera;
            @Tera.performed -= instance.OnTera;
            @Tera.canceled -= instance.OnTera;
            @BabyBalensiagaFlying.started -= instance.OnBabyBalensiagaFlying;
            @BabyBalensiagaFlying.performed -= instance.OnBabyBalensiagaFlying;
            @BabyBalensiagaFlying.canceled -= instance.OnBabyBalensiagaFlying;
            @FireMan.started -= instance.OnFireMan;
            @FireMan.performed -= instance.OnFireMan;
            @FireMan.canceled -= instance.OnFireMan;
            @CameraMoveAround.started -= instance.OnCameraMoveAround;
            @CameraMoveAround.performed -= instance.OnCameraMoveAround;
            @CameraMoveAround.canceled -= instance.OnCameraMoveAround;
            @CameraOutIn.started -= instance.OnCameraOutIn;
            @CameraOutIn.performed -= instance.OnCameraOutIn;
            @CameraOutIn.canceled -= instance.OnCameraOutIn;
            @ResetPos.started -= instance.OnResetPos;
            @ResetPos.performed -= instance.OnResetPos;
            @ResetPos.canceled -= instance.OnResetPos;
            @ResetRot.started -= instance.OnResetRot;
            @ResetRot.performed -= instance.OnResetRot;
            @ResetRot.canceled -= instance.OnResetRot;
        }

        public void RemoveCallbacks(IMappingActions instance)
        {
            if (m_Wrapper.m_MappingActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMappingActions instance)
        {
            foreach (var item in m_Wrapper.m_MappingActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MappingActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MappingActions @Mapping => new MappingActions(this);
    private int m_MappingSchemeSchemeIndex = -1;
    public InputControlScheme MappingSchemeScheme
    {
        get
        {
            if (m_MappingSchemeSchemeIndex == -1) m_MappingSchemeSchemeIndex = asset.FindControlSchemeIndex("MappingScheme");
            return asset.controlSchemes[m_MappingSchemeSchemeIndex];
        }
    }
    public interface IMappingActions
    {
        void OnGraceWhite(InputAction.CallbackContext context);
        void OnGraceLila(InputAction.CallbackContext context);
        void OnBabyBalenciaga(InputAction.CallbackContext context);
        void OnMuscleMan(InputAction.CallbackContext context);
        void OnTera(InputAction.CallbackContext context);
        void OnBabyBalensiagaFlying(InputAction.CallbackContext context);
        void OnFireMan(InputAction.CallbackContext context);
        void OnCameraMoveAround(InputAction.CallbackContext context);
        void OnCameraOutIn(InputAction.CallbackContext context);
        void OnResetPos(InputAction.CallbackContext context);
        void OnResetRot(InputAction.CallbackContext context);
    }
}
